[package]
name = "docker-openapi"
version = "0.0.1"
authors = ["insanitybit@github.com"]
edition = "2021"

[dependencies]
futures = "0.3.25"
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.152"
serde_json = "1.0.91"

[dev-dependencies]
tokio-core = "*"
